
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthTime
      max_allowed_packet: 64M
    ports:
      - "3306:3306" 
    volumes:    
      - ./healthTime.sql:/docker-entrypoint-initdb.d/healthTime.sql
    networks:
      - health-time-net
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    ports:
      - "8087:80"
    networks:
      - health-time-net

    

  backend:
    build:
      context: ./healthtime-backend
    ports:
      - "8888:8888"
    depends_on:
      mysql:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthTime
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - health-time-net
    restart: always

  frontend:
    build:
      context: ./healthtime-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

networks:
  health-time-net:
    driver: bridge